const STATUS_COLORS = {
  TICKET_CREATED: "#F9BD0E",
  PACKAGE_RECEIVED: "#F9BD0E",
  OUT_FOR_DELIVERY: "#F9BD0E",
  DELIVERED: "#1ac45e",
  DELIVERED_TO_SENDER: "#1ac45e",
  CANCELLED: "#F40105",
};

export default STATUS_COLORS;
